### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by nebfield** [intervene-EU-H2020/prs-method-compare#10]
- [x] Explain what metric means on figures (link out to glossary?)
- [x] Use clear language instead of maths for the axis labels
- [x] Fix missing facets, covered by:
  - [x] #4 
  - [x] https://github.com/intervene-EU-H2020/pgsCompaR/issues/2
- [x] Add preprint links
